version: "3.3"

networks:
  proxy:
    external: { }

services:
  grpc-proxy:
    image: "traefik:v3.1"
    container_name: "traefik"

    #      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=POST,GET,OPTIONS,PUT"
    #      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*"
    #      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
    #      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"

    ports:
      - "1234:1234"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
    networks:
      - proxy
