global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: :1234

providers:
  file:
    directory: /etc/traefik/
  docker:
    exposedByDefault: false
