name: Rust-Checks

on:
  pull_request:
  push:
    branches: main

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: ./.github/actions/install-rust-toolchain
        with:
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: ./.github/actions/install-rust-toolchain
        with:
          components: clippy

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --lib -- -D warnings -A deprecated
