name: Test-Format-Clippt

on: [pull_request]

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: ./.github/actions/install-rust-toolchain

      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: ./.github/actions/install-rust-toolchain
        with:
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: ./.github/actions/install-rust-toolchain
        with:
          components: clippy
          
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets -- -D warnings
